wandb_version: 1

general:
  desc: null
  value:
    project: GC
    name: CMLP
data_path:
  desc: null
  value:
  - ../data/A_endogenous.pickle
  - ../data/B_latent.pickle
  - ../data/C_retail_latent.pickle
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688079222.84034
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.15.4
      8:
      - 5
