model:
  device: 'cuda'
  lag: 1
  hidden: 100
  lam: 0.0022
  lam_ridge: 0.015
  lr: 0.05
  penalty: 'H'
  max_iter: 20000
  check_every: 100
  activation: 'tanh'
  prime: False
  composed: True
  composed_count: 2