# wandb:
#   project: 'GC'
#   name: 'CMLP'

# data:
#   catagory: 'retail_latent'

model:
  device: 'cuda'
  lag: 1
  hidden: 100
  lam: 0.002
  lam_ridge: 0.01
  lr: 0.05
  penalty: 'H'
  max_iter: 50000
  check_every: 100
  activation: 'tanh'